KHP3: (refactor) migrate procedures order panel and order form to radiology app
palladiumkenya/esm-procedure-app pull request #15
Opened 2024-03-25 19:04 UTC by donaldkibet

## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Summary
This PR migrates procedure related features to esm-procedure. Initial work done by @PatrickWaweru 

## Screenshots
Uploading Kapture 2024-03-25 at 22.01.35.mp4…

## Related Issue

## Other

2024-03-25 19:47 UTC, ojwanganto requested changes
Thanks, @donaldkibet. I think we can generally favour ProcedureOrder instead of ProceduresOrder

2024-03-25 19:47 UTC, ojwanganto commented on src/config-schema.ts
>    casualGreeting: boolean;
Where have we used these?

2024-03-25 19:47 UTC, ojwanganto commented on src/form/procedures-orders/add-procedures-order/add-procedures-order.workspace.tsx
> +export interface AddProceduresOrderWorkspaceAdditionalProps {
Ideally, this should read something like **AddProcedureOrderWorkspaceAdditionalProps**

2024-03-25 19:47 UTC, ojwanganto commented on src/form/procedures-orders/add-procedures-order/procedures-order.ts
> +export function createEmptyLabOrder(
you may have been thinking about empty procedure order

2024-03-25 19:47 UTC, ojwanganto commented on src/form/procedures-orders/add-procedures-order/procedures-type-search.tsx
> +  openLabForm: (searchResult: ProceduresOrderBasketItem) => void;
I would go for ProcedureOrderBasketItem

2024-03-26 07:49 UTC, donaldkibet commented on src/form/procedures-orders/add-procedures-order/procedures-order.ts
> +export function createEmptyLabOrder(
Haven't thought about that, just moving the files over to esm-procedure-app

2024-03-26 10:05 UTC, ojwanganto commented on src/form/procedures-orders/add-procedures-order/procedures-order.ts
> +export function createEmptyLabOrder(
I basically was referring to the name: **createEmptyLabOrder**. It should be something emptyProcedureOrder or something, ama?

2024-03-27 20:20 UTC, donaldkibet commented
Merging this now since most of the requested changes have been addressed. Will address subsequent changes in another PR if need be. Thanks @ojwanganto

2024-03-27 20:20 UTC, merged

2024-03-27 21:17 UTC, ojwanganto commented
Thanks @donaldkibet