cleaned the procedure order form
palladiumkenya/esm-procedure-app pull request #33
Opened 2024-04-16 11:46 UTC by agesa3

## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Summary

## Screenshots

<img width="369" alt="Screenshot 2024-04-16 at 14 42 50" src="https://github.com/palladiumkenya/esm-procedure-app/assets/47299413/0559d377-5ec9-4432-9a23-7c2b209e9a6d">

## Related Issue

## Other

2024-04-16 12:37 UTC, jecihjoy approved these changes
Hi @agesa3 was this  requested by the BA, if yes we can try to make it a selectable list which can pick of a `concept set`

2024-04-17 21:06 UTC, jecihjoy commented
I will defer this to @ojwanganto to help advice whether we need three different sections (body site, additional instructions and comments to fulfiller) for captuire procedure ordering information

2024-04-18 05:48 UTC, ojwanganto requested changes

2024-04-18 05:48 UTC, ojwanganto commented on src/form/procedures-orders/add-procedures-order/procedures-order-form.component.tsx
> +  } = useConceptById("162668AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
can we use a config for this?

2024-04-18 05:48 UTC, ojwanganto commented
@donaldkibet - please re-review this.

2024-04-18 06:11 UTC, donaldkibet approved these changes
Thanks @agesa3 LGTM

2024-04-18 10:08 UTC, ojwanganto commented
So my thoughts are:
**body site:** is the target body part for the procedure, 
**additional instructions:**  this is instructions about the procedure and 
**comments to fulfiller:** is anything you would want to communicate to the person handling the procedure

@jecihjoy - do you see conflicts?

2024-04-19 04:08 UTC, jecihjoy commented
> So my thoughts are: **body site:** is the target body part for the procedure, **additional instructions:** this is instructions about the procedure and **comments to fulfiller:** is anything you would want to communicate to the person handling the procedure
> 
> @jecihjoy - do you see conflicts?

Makes sense, we can proceed with the changes

2024-04-19 12:28 UTC, merged