Procedure order fixes
palladiumkenya/esm-procedure-app pull request #58
Opened 2024-07-11 23:11 UTC by its-kios09

## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Summary

- fixed **Uncaught TypeError: (0 , w.closeWorkspace) is not a function** error on order basket
- added ability to show procedure prices on the order basket

## Screenshots
![procedure](https://github.com/user-attachments/assets/c65e63d9-fb2c-4f35-9575-7c0491bdd998)

## Related Issue

## Other

2024-07-12 05:37 UTC, makombe reviewed
Thanks @its-kios09  LGTM

2024-07-12 05:37 UTC, makombe commented on src/form/procedures-orders/add-procedures-order/procedures-order-form.component.tsx
> +                        {t("mode", "payment methods")}
```suggestion
                        {t("paymentMethods", "Payment methods")}
```

2024-07-12 05:37 UTC, makombe commented on src/form/procedures-orders/add-procedures-order/procedures-order-form.component.tsx
> +                        {t("prices", "prices")}
```suggestion
                        {t("prices", "Prices")}
```

2024-07-12 06:07 UTC, donaldkibet requested changes
Thanks @its-kios09

2024-07-12 06:07 UTC, donaldkibet commented on src/form/procedures-orders/api.ts
> +};
We should not be handling billing information and work on the procedure repo. We should have an extension-slot then implement the logic of retrieving prices from esm-billing-app. something like this https://github.com/openmrs/openmrs-esm-patient-chart/blob/eea68c63846af39892bdf2e6bc1d08dc9fcc4824/packages/esm-patient-labs-app/src/lab-orders/add-lab-order/lab-order-form.component.tsx#L170 and logic is here
for lab and drug orders https://github.com/palladiumkenya/kenyaemr-esm-3.x/tree/main/packages/esm-billing-app/src/billable-services/billiable-item

I think Ted will also need to align with the design. The initial work wasn't informed on any designs

2024-07-12 22:12 UTC, its-kios09 commented
Reviewed the code and created another PR

2024-07-12 22:12 UTC, closed without merging

2024-07-15 06:02 UTC, ojwanganto commented
@its-kios09 - Please avoid new PRs. We need to keep the review history.