(fix) updated the procedures app UI by grouping orders by patient
palladiumkenya/esm-procedure-app pull request #61
Opened 2024-07-29 12:50 UTC by FelixKiprotich350

## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Summary
fixed the grouping of orders by patient and displaying the name of the patient alongside his/her total orders pending

## Screenshots
**screen shot**
![Screenshot from 2024-07-29 15-48-50](https://github.com/user-attachments/assets/b518e663-dc2d-497d-bccb-d7eac2260477)
**screen record**
[procedures-grouping.webm](https://github.com/user-attachments/assets/478dab69-7e31-46b5-8265-5593c2bd9bf4)

## Related Issue

## Other

2024-07-29 12:50 UTC, FelixKiprotich350 commented
@makombe  , @donaldkibet and @ojwanganto have a look

2024-07-29 21:47 UTC, ojwanganto commented
Thanks, @FelixKiprotich350. cc @makombe @donaldkibet

2024-07-30 06:49 UTC, makombe commented on src/common/commonProps.resource.ts
> +  displayPosition: 0 | number;
we can name this file appropriately, seems to be types and not resource

2024-07-30 06:49 UTC, makombe commented on src/common/listOrderDetails.scss
> +    margin-top: 2rem;
Preferably use carbon spacing

2024-07-30 06:52 UTC, makombe reviewed
Thanks @FelixKiprotich350

2024-07-30 06:52 UTC, makombe commented on src/common/groupedOrdersTable.component.tsx
> +                        t("filterOrdersByStatus", "Filter Orders by status") +
```suggestion
                        t("filterOrdersByStatus", "Filter orders by status") +
```

2024-07-30 06:52 UTC, makombe commented on src/common/groupedOrdersTable.component.tsx
> +                      {t("noOrderAvailable", "No Orders Availalble")}
```suggestion
                      {t("noOrderAvailable", "No orders available")}
```

2024-07-30 06:53 UTC, makombe commented on src/common/groupedOrdersTable.component.tsx
> +                      {t("noOrderAvailable", "No Orders Availalble")}
Can you also re-attach the video not able to view the attached.

2024-07-30 07:17 UTC, donaldkibet commented on src/common/commonProps.resource.ts
> +  displayPosition: 0 | number;
types and interfaces should be centralized on `types/index.ts` file

2024-07-30 07:24 UTC, donaldkibet requested changes

2024-07-30 07:24 UTC, donaldkibet commented on src/common/groupedOrdersTable.component.tsx
> +  const [searchString, setSearchString] = useState<string>("");
We should removed unused imports

2024-07-30 07:24 UTC, donaldkibet commented on src/common/groupedOrdersTable.component.tsx
> +  const [filter, setFilter] = useState<
Maybe having this as a type e.g 

```tsx
type FilterType = 
  | "All"
  | "EXCEPTION"
  | "RECEIVED"
  | "COMPLETED"
  | "IN_PROGRESS"
  | "ON_HOLD"
  | "DECLINED";

const [filter, setFilter] = useState<FilterType>("All");
```

2024-07-30 07:24 UTC, donaldkibet commented on src/common/groupedOrdersTable.component.tsx
> +  const [filter, setFilter] = useState<
we can extract and store in the file storing types

2024-07-30 07:24 UTC, donaldkibet commented on src/common/groupedOrdersTable.component.tsx
> +  const pageSizes = [10, 20, 30, 40, 50];
use `usePaginationInfo` hook to generate this pageSizes its imported from `@openmrs/esm-framework`

2024-07-30 07:24 UTC, donaldkibet commented on src/common/groupedOrdersTable.component.tsx
> +  const rowsdata = useMemo(() => {
```suggestion
  const rowsData = useMemo(() => {
```

2024-07-30 07:24 UTC, donaldkibet commented on src/common/groupedOrdersTable.component.tsx
> +      patientname: patient.orders[0].patient?.display?.split("-")[1],
```suggestion
      patientName: patient.orders[0].patient?.display?.split("-")[1],
```
please use camelCase

2024-07-30 07:24 UTC, donaldkibet commented on src/common/groupedOrdersTable.component.tsx
> +    { id: 0, header: t("patient", "Patient"), key: "patientname" },
```suggestion
    { id: 0, header: t("patient", "Patient"), key: "patientName" },
```

2024-07-30 07:24 UTC, donaldkibet commented on src/common/groupedOrdersTable.component.tsx
> +                <Layer style={{ margin: "5px" }}>
please extract styles to styles sheet

2024-07-30 07:24 UTC, donaldkibet commented on src/common/groupedOrdersTable.scss
> +@use '@carbon/styles/scss/spacing';
```suggestion
@use '@carbon/layout';
```

2024-07-30 19:14 UTC, FelixKiprotich350 commented
@donaldkibet , @ojwanganto  and @makombe .... verify if l left out something on the requested changes

2024-07-31 09:12 UTC, donaldkibet approved these changes

2024-08-02 05:19 UTC, merged